openapi: 3.0.3
info:
  title: Agent Service API
  description: Individual agent endpoint powered by Claude Agent SDK
  version: 1.0.0
servers:
  - url: http://localhost:8001
    description: Agent 1
  - url: http://localhost:8002
    description: Agent 2
  - url: http://localhost:8003
    description: Agent 3
  - url: http://localhost:8004
    description: Agent 4
  - url: http://localhost:8005
    description: Agent 5

paths:
  /health:
    get:
      summary: Health check
      description: Returns agent health status and SDK version
      operationId: healthCheck
      responses:
        '200':
          description: Agent is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  agent_id:
                    type: string
                    example: "agent_1"
                  is_available:
                    type: boolean
                  current_task:
                    type: string
                    nullable: true
                  sdk_version:
                    type: string
                    example: "claude-agent-sdk-1.0"

  /status:
    get:
      summary: Get detailed agent status
      description: Returns comprehensive status including resource usage and capabilities
      operationId: getAgentStatus
      responses:
        '200':
          description: Agent status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentStatus'

  /execute:
    post:
      summary: Execute a subtask
      description: Accepts a subtask for execution using Claude Agent SDK
      operationId: executeSubTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskExecutionRequest'
      responses:
        '200':
          description: Subtask accepted for execution (runs in background)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [accepted]
                  agent_id:
                    type: string
        '503':
          description: Agent is busy executing another task
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Agent busy"

components:
  schemas:
    TaskExecutionRequest:
      type: object
      required:
        - task_id
        - subtask
      properties:
        task_id:
          type: string
          description: Parent task identifier
        subtask:
          $ref: '#/components/schemas/SubTask'
        task_context:
          type: object
          description: Results from prerequisite subtasks
          additionalProperties: true

    SubTask:
      type: object
      required:
        - id
        - description
        - required_capabilities
      properties:
        id:
          type: string
          example: "subtask_abc123"
        description:
          type: string
          example: "Fetch and parse data from API"
        required_capabilities:
          type: array
          items:
            type: string
            enum: [data_analysis, web_scraping, code_generation, file_processing, database_operations, api_integration]
          minItems: 1
        dependencies:
          type: array
          items:
            type: string
          default: []
        priority:
          type: integer
          minimum: 0
          maximum: 10
          default: 5
        estimated_duration:
          type: integer
          nullable: true
          description: Estimated seconds to complete
        input_data:
          type: object
          additionalProperties: true
          default: {}

    AgentStatus:
      type: object
      required:
        - agent_id
        - port
        - is_available
        - capabilities
        - cpu_usage
        - memory_usage
        - tasks_completed
      properties:
        agent_id:
          type: string
        port:
          type: integer
        is_available:
          type: boolean
        current_task:
          type: string
          nullable: true
        capabilities:
          type: array
          items:
            type: string
        cpu_usage:
          type: number
          format: float
        memory_usage:
          type: number
          format: float
        tasks_completed:
          type: integer
